server:
  port: ${PORT:8089}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: false
    hostname: ${IAM_HOSTNAME}
    non-secure-port: 443
    secure-port-enabled: true

spring:
  data:
    redis:
      url: ${REDIS_URL_PROD}
